name: Deno

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build deno application on ${{ matrix.deno }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        deno: ["2.3.6"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Get tag
        run: |
          VERSION=$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' package.json)
          echo "TAG=v$VERSION" >> $GITHUB_OUTPUT
        id: get_tag

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Build and zip
        run: npm run build:zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.get_tag.outputs.TAG }}
          tag: ${{ steps.get_tag.outputs.TAG }}
          artifacts: "dist/*.zip"
          body: Fixes and features ;)
          token: ${{ secrets.GH_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "var-rocks"
          entrypoint: "./var.rocks/server.ts"
